float32 azimuth_angle
float32 azimuth_angle_std
bool invalid_distance
bool invalid_distance_std
bool invalid_azimuth
bool invalid_azimuth_std
bool invalid_elevation
bool invalid_elevation_std
bool invalid_range_rate
bool invalid_range_rate_std
float32 elevation_angle
float32 elevation_angle_std
float32 range
float32 range_std
float32 range_rate
float32 range_rate_std
int8 rcs
uint16 measurement_id
uint8 raw_positive_predictive_value # 0 ~ 100
uint8 classification
uint8 raw_multi_target_probability # 0 ~ 100
uint16 object_id
uint8 raw_ambiguity_flag # 0 ~ 100
