coverage:
  status:
    project:
      default:
        target: auto
        # allow slight decreases in coverage compared to the base ref
        threshold: 1%

ignore:
  - ^build.* # for generated message wrappers
  - ^nebula_examples.* # not safety-related

comment:
  layout: header, diff, flags, components

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
  individual_flags:
    - name: Core
      paths:
        - src/nebula_core
    - name: Hesai
      paths:
        - src/nebula_hesai
    - name: Velodyne
      paths:
        - src/nebula_velodyne
    - name: Continental
      paths:
        - src/nebula_continental
    - name: Robosense
      paths:
        - src/nebula_robosense
