ignore:
  - ^build.* # for generated message wrappers

comment:
  layout: header, diff, flags, files

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: Core
      paths:
        - src/nebula_core
    - name: Hesai
      paths:
        - src/nebula_hesai
    - name: Velodyne
      paths:
        - src/nebula_velodyne
    - name: Continental
      paths:
        - src/nebula_continental
    - name: Robosense
      paths:
        - src/nebula_robosense
