/**:
  ros__parameters:
    sensor_model: "RobosenseHelios"  # See readme for supported models
    frame_id: "robosense"   
    return_mode: "Dual"
    lidar_ip: "192.168.1.200"     # Lidar Sensor IP
    host_ip: "192.168.1.102"    
    data_port: 6699     # Lidar Data Port
    difop_port: 7788   #Lidar Info Output Protocol Port
    packet_mtu_size: 1500  # Packet MTU size
    rotation_speed: 600    # Motor RPM, the sensor's internal spin rate.
    cloud_min_angle: 0   # Field of View, start degrees.
    cloud_max_angle: 360  # Field of View, end degrees.
    calibration_file: "./install/nebula_decoders/share/nebula_decoders/calibration/robosense/RobosenseHelios.csv"
    setup_sensor: True
    online: True