/**:
  ros__parameters:
    sensor_model: "RobosenseE1"
    frame_id: "robosense"
    return_mode: "Dual"
    lidar_ip: "198.18.35.6"
    host_ip: "198.18.35.102"
    data_port: 31003
    difop_port: 31004
    packet_mtu_size: 1500
    rotation_speed: 600
    cloud_min_angle: 0
    cloud_max_angle: 360
    calibration_file: "./install/nebula_decoders/share/nebula_decoders/calibration/robosense/RobosenseE1.csv"
    setup_sensor: True
    online: True