/**:
  ros__parameters:
    host_ip: 172.168.1.100
    sensor_ip: 172.168.1.10
    udp_port: 8010
    sensor_model: RobinE1X
    use_sensor_time: false
    frame_id: seyond
    setup_sensor: true
    return_mode: Single
    reflectance_mode: Reflectivity
    time_sync: Host
