nebula_hesai_hw_interface:
  ros__parameters:
    sensor_model: "Pandar64"
    device_ip: "192.168.1.201"
    host_ip: "255.255.255.255"
    frame_id: "pandar"
    data_port: 2368
    gnss_port: 2369
    online: True