name: build-and-test-differential

on:
  pull_request:

jobs:
  build-and-test-differential:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        include:
          - rosdistro: humble
            container: ros:humble
            build-depends-repos: build_depends.repos
    env:
      CCACHE_DIR: /root/.ccache
      CC: /usr/lib/ccache/gcc
      CXX: /usr/lib/ccache/g++

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Install ccache
        run: sudo apt-get -yqq update && sudo apt-get -yqq install ccache
        shell: bash

      - name: Create ccache directory
        run: |
          mkdir -p ${CCACHE_DIR}
          du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Attempt to restore ccache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${CCACHE_DIR}
          key: ccache-${{ runner.arch }}-${{ matrix.rosdistro }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ccache-${{ runner.arch }}-${{ matrix.rosdistro }}-

      - name: Show ccache stats before build and reset stats
        run: |
          du -sh ${CCACHE_DIR} && ccache -s
          ccache --zero-stats
        shell: bash

      - name: Build
        id: build
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Show ccache stats after build
        run: |
          du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Test
        id: test
        if: ${{ steps.build.outcome == 'success' }}
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Upload coverage to CodeCov
        if: ${{ steps.test.outputs.coverage-report-files != '' }}
        uses: codecov/codecov-action@v4
        with:
          files: ${{ steps.test.outputs.coverage-report-files }}
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
          flags: differential

  fb-infer-differential:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        include:
          - rosdistro: humble
            container: ros:humble
            build-depends-repos: build_depends.repos
    env:
      CCACHE_DIR: /root/.ccache
      INFER_REPORT_PARENT_DIR: /tmp
      CC: /usr/lib/ccache/clang-15
      CXX: /usr/lib/ccache/clang++-15
    steps:
      ########################################
      # Feature branch analysis
      ########################################

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages-feature
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Install Clang-15 and ccache
        run: |
          sudo apt-get -yqq update
          sudo apt-get -yqq install --install-recommends clang-15 clang-tidy-15 clangd-15
          sudo apt-get -yqq install clang-15-doc wasi-libc llvm-15-doc
          sudo apt-get -yqq install libomp-15-dev libomp-15-doc # For OpenMP support in Clang
          sudo apt-get -yqq install libstdc++-12-dev
          sudo apt-get -yqq install ccache

      - name: Create ccache directory
        run: |
          mkdir -p ${CCACHE_DIR}
          du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Attempt to restore ccache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${CCACHE_DIR}
          key: ccache-${{ runner.arch }}-${{ matrix.rosdistro }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ccache-${{ runner.arch }}-${{ matrix.rosdistro }}-

      - name: Install FB Infer
        id: fb-infer-install
        if: ${{ steps.get-modified-packages-feature.outputs.modified-packages != '' }}
        env:
          VERSION: 1.2.0
        run: |
          export BASENAME="infer-linux-x86_64-v${VERSION}"
          export FILENAME="${BASENAME}.tar.xz"
          sudo apt-get -yqq install curl tar
          curl -sSLO "https://github.com/facebook/infer/releases/download/v${VERSION}/${FILENAME}"
          tar -xf "$FILENAME"
          rm "$FILENAME"
          sudo mv "$BASENAME" /usr/local/infer
          echo "PATH=/usr/local/infer/bin:$PATH" >> $GITHUB_ENV

      - name: Show ccache stats before build and reset stats
        run: |
          du -sh ${CCACHE_DIR} && ccache -s
          ccache --zero-stats
        shell: bash

      - name: Build feature branch
        id: build-feature
        if: ${{ steps.get-modified-packages-feature.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-modified-packages-feature.outputs.modified-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Show ccache stats after build
        run: |
          du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Analyze feature branch
        id: analyze-feature
        if: ${{ steps.get-modified-packages-feature.outputs.modified-packages != '' }}
        run: |
          # Run infer on feature branch
          infer capture --compilation-database build/compile_commands.json
          infer analyze

          # Store feature branch report
          mv infer-out ${INFER_REPORT_PARENT_DIR}/infer-out-feature

      ########################################
      # Main branch analysis
      ########################################

      - name: Restore main branch infer cache
        id: cache-infer-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.INFER_REPORT_PARENT_DIR }}/infer-out-main
          key: infer-main-${{ github.base_ref }}-${{ github.event.pull_request.base.sha }}
          restore-keys: |
            infer-main-${{ github.base_ref }}-

      - name: Checkout main branch
        id: checkout-main
        if: ${{ steps.cache-infer-restore.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.base_ref }}

      - name: Remove exec_depend
        if: ${{ steps.cache-infer-restore.outputs.cache-hit != 'true' }}
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Show ccache stats before build and reset stats
        run: |
          du -sh ${CCACHE_DIR} && ccache -s
          ccache --zero-stats
        shell: bash

      - name: Build main branch
        id: build-main
        if: ${{ steps.cache-infer-restore.outputs.cache-hit != 'true' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-modified-packages-feature.outputs.modified-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Show ccache stats after build
        run: |
          du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Cache ccache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.arch }}-${{ matrix.rosdistro }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Analyze main branch
        id: analyze-main
        if: ${{ steps.cache-infer-restore.outputs.cache-hit != 'true' }}
        run: |
          # Run infer on feature branch
          infer capture --compilation-database build/compile_commands.json
          infer analyze

          # Store main branch report
          mv infer-out ${INFER_REPORT_PARENT_DIR}/infer-out-main

      - name: Cache main branch infer results
        if: ${{ steps.cache-infer-restore.outputs.cache-hit != 'true' && steps.analyze-main.outcome == 'success' }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.INFER_REPORT_PARENT_DIR }}/infer-out-main
          key: infer-main-${{ github.base_ref }}-${{ github.event.pull_request.base.sha }}

      ########################################
      # Differential analysis
      ########################################

      - name: Compare reports
        if: ${{ steps.analyze-feature.outcome == 'success' }}
        run: |
          infer reportdiff \
            --report-current ${INFER_REPORT_PARENT_DIR}/infer-out-feature/report.json \
            --report-previous ${INFER_REPORT_PARENT_DIR}/infer-out-main/report.json
          mv infer-out ${INFER_REPORT_PARENT_DIR}/infer-out-differential

      - name: Upload FB Infer Reports
        id: upload-infer-reports
        uses: actions/upload-artifact@v4
        with:
          name: infer-reports-${{ github.sha }}
          path: |
            ${{ env.INFER_REPORT_PARENT_DIR }}/infer-out-feature/report.json
            ${{ env.INFER_REPORT_PARENT_DIR }}/infer-out-differential/*
          if-no-files-found: error

      - name: Generate Infer summary
        id: generate-infer-summary
        if: ${{ steps.analyze-feature.outcome == 'success' }}
        run: |
          python .github/workflows/scripts/summarize-infer-diff.py \
            ${INFER_REPORT_PARENT_DIR}/infer-out-differential \
            ${{ steps.upload-infer-reports.outputs.artifact-url }} \
            ${INFER_REPORT_PARENT_DIR}/infer-summary.md

      - name: Find Comment
        if: ${{ steps.generate-infer-summary.outcome == 'success' }}
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: FB Infer Differential Analysis

      # If the comment-id is empty, this creates a new comment
      - name: Post or update PR comment
        if: ${{ steps.generate-infer-summary.outcome == 'success' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: ${{ env.INFER_REPORT_PARENT_DIR }}/infer-summary.md
          edit-mode: replace
