name: cancel-previous-workflows

on:
  pull_request_target:

jobs:
  cancel-previous-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: all
          all_but_latest: true
